import type { Metadata } from "next";
import { Lexend, } from "next/font/google";
import "./globals.css";
import { NextuiProviders } from "@/provider/NextUIProvider";

const lexendSans = Lexend({
  variable: "--font-lexend",
  subsets: ["vietnamese"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendSans.className} font-sans antialiased relative`}>
        <NextuiProviders>
          <main className="h-screen">
            {children}
          </main>
        </NextuiProviders>
      </body>
    </html>
  );
}
